### ISSUE TITLE
ruby 2.0 errors with gem install

### ISSUE THREAD

**Issue by auxsoft** [TritonDataCenter/pkgsrc-legacy#162]
With a fresh install of package ruby200-2.0.0

```
gem install somegem
```

gives error

```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `empty?' for nil:NilClass
        /opt/local/lib/ruby/2.0.0/rubygems/installer.rb:575:in `process_options'
        /opt/local/lib/ruby/2.0.0/rubygems/installer.rb:120:in `initialize'
        /opt/local/lib/ruby/2.0.0/rubygems/dependency_installer.rb:374:in `new'
        /opt/local/lib/ruby/2.0.0/rubygems/dependency_installer.rb:374:in `block in install'
        /opt/local/lib/ruby/2.0.0/rubygems/dependency_installer.rb:347:in `each'
        /opt/local/lib/ruby/2.0.0/rubygems/dependency_installer.rb:347:in `each_with_index'
        /opt/local/lib/ruby/2.0.0/rubygems/dependency_installer.rb:347:in `install'
        /opt/local/lib/ruby/2.0.0/rubygems/commands/install_command.rb:166:in `block in execute'
        /opt/local/lib/ruby/2.0.0/rubygems/commands/install_command.rb:158:in `each'
        /opt/local/lib/ruby/2.0.0/rubygems/commands/install_command.rb:158:in `execute'
        /opt/local/lib/ruby/2.0.0/rubygems/command.rb:305:in `invoke_with_build_args'
        /opt/local/lib/ruby/2.0.0/rubygems/command_manager.rb:170:in `process_args'
        /opt/local/lib/ruby/2.0.0/rubygems/command_manager.rb:130:in `run'
        /opt/local/lib/ruby/2.0.0/rubygems/gem_runner.rb:60:in `run'
        /opt/local/bin/gem200:21:in `<main>'
```

That traces back to this pkgsrc patch:

``` diff
+    if not @install_root.empty?
+      @bin_dir = File.join(@install_root, @bin_dir)
+    end
```

https://github.com/joyent/pkgsrc/blob/3dc2648a8d9aa295d6bc4cff9310aa596b6846bd/lang/ruby200-base/patches/patch-lib_rubygems_installer.rb#L34

**Comment by mamash** [comment]
Thanks, that condition needs a check @install_root.nil? too. I'll fix upstream and backport to 2013Q3.

**Comment by auxsoft** [comment]
Yes. I patched my installation with `unless @install_root.nil? || @install_root.empty?` . I don't know why install_root is needed, though.

**Comment by mamash** [comment]
It's for pkgsrc's own ruby-\* packages. pkgsrc always installs into a DESTDIR sandbox when creating a binary package.

**Comment by mamash** [comment]
This was fixed earlier.
