### ISSUE TITLE
python: ImportError: No module named _elementtree (python26, python27, 2013Q3, 2014Q1, x86_64)

### ISSUE THREAD

**Issue by AlainODea** [TritonDataCenter/pkgsrc-legacy#199]
It looks like the built-in Python xml package is missing **_elementtree**.  

System configuration:

``` bash
# cat /etc/product 
Name: Joyent Instance
Image: base64 14.1.0
Documentation: http://wiki.joyent.com/jpc2/SmartMachine+Base
# cat /etc/pkgsrc_version 
release: 2014Q1
architecture: x86_64
```

``` python
Traceback (most recent call last):
  File "/opt/local/bin/aws", line 15, in <module>
    import awscli.clidriver
  File "/opt/local/lib/python2.7/site-packages/awscli/clidriver.py", line 16, in <module>
    import botocore.session
  File "/opt/local/lib/python2.7/site-packages/botocore/session.py", line 33, in <module>
    import botocore.service
  File "/opt/local/lib/python2.7/site-packages/botocore/service.py", line 17, in <module>
    from .endpoint import get_endpoint
  File "/opt/local/lib/python2.7/site-packages/botocore/endpoint.py", line 24, in <module>
    import botocore.response
  File "/opt/local/lib/python2.7/site-packages/botocore/response.py", line 16, in <module>
    import xml.etree.cElementTree
  File "/opt/local/lib/python2.7/xml/etree/cElementTree.py", line 3, in <module>
    from _elementtree import *
ImportError: No module named _elementtree
```

Steps to reproduce on Python 2.7:

``` bash
pkgin in py27-pip
pip install awscli
aws
```

This also happens on python 2.6:

``` python
Traceback (most recent call last):
  File "/opt/local/bin/aws", line 15, in <module>
    import awscli.clidriver
  File "/opt/local/lib/python2.6/site-packages/awscli/clidriver.py", line 16, in <module>
    import botocore.session
  File "/opt/local/lib/python2.6/site-packages/botocore/session.py", line 33, in <module>
    import botocore.service
  File "/opt/local/lib/python2.6/site-packages/botocore/service.py", line 17, in <module>
    from .endpoint import get_endpoint
  File "/opt/local/lib/python2.6/site-packages/botocore/endpoint.py", line 24, in <module>
    import botocore.response
  File "/opt/local/lib/python2.6/site-packages/botocore/response.py", line 16, in <module>
    import xml.etree.cElementTree
  File "/opt/local/lib/python2.6/xml/etree/cElementTree.py", line 3, in <module>
    from _elementtree import *
ImportError: No module named _elementtree
```

Steps to reproduce on Python 2.6:

``` bash
pkgin -y rm python26
pkgin in py26-pip
pip install awscli
aws
```

This is also identically reproducible on this system configuration:

``` bash
# cat /etc/pkgsrc_version 
release: 2013Q3
architecture: x86_64
# cat /etc/product 
Name: Joyent Instance
Image: base64 13.3.1
Documentation: http://wiki.joyent.com/jpc2/SmartMachine+Base
```

**Comment by mamash** [comment]
Did you try with py27-elementtree or py27-cElementTree?

pkgsrc always strives to be as modular as possible...

**Comment by AlainODea** [comment]
PEBKAC on my part.  Thank you @mamash, that worked perfectly.

**Comment by AlainODea** [comment]
Specifically had to run:

```
pkgin -y install py27-cElementTree
```

After that the aws cli works.
