### ISSUE TITLE
devel/apache-maven version 3.2.1 misses directory /opt/local/conf/logging

### ISSUE THREAD

**Issue by mjansens** [TritonDataCenter/pkgsrc-legacy#223]
Hi,
I  installed the latest apache-maven:
pkgin in apache-maven-3.2.1 
cat pkg_install.conf 
PKG_PATH=http://pkgsrc.joyent.com/packages/SmartOS/2014Q2/x86_64/All

Now mvn complains for some missing directory:

mvn -version
java.io.FileNotFoundException: /opt/local/conf/logging
    at org.codehaus.plexus.classworlds.launcher.ConfigurationParser.parse(ConfigurationParser.java:264)
    at org.codehaus.plexus.classworlds.launcher.Configurator.configure(Configurator.java:133)
    at org.codehaus.plexus.classworlds.launcher.Launcher.configure(Launcher.java:131)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

mkdir -p  /opt/local/conf/logging fixed the problem for me.

Best regards,

Michel

**Comment by mamash** [comment]
I fixed this in upstream pkgsrc (together with the bump to 3.2.3) and will bring this fix back to 2014Q3 at least.
