### ISSUE TITLE
py27-pip broken after pkgin -fy up; pkgin -fy upgrade

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc-legacy#326]
py27-pip is broken after:

``` bash
pkgin -fy up
pkgin -y upgrade
```

The latest openssl with SSLv2 remove seems to break it.

``` bash
pkgin -fy in py27-OpenSSL
```

To force a reinstall does not seem to fix the issue.

**Comment by sjorge** [comment]
``` bash
[root@test ~]# pip
Traceback (most recent call last):
  File "/opt/local/bin/pip2.7", line 9, in <module>
    load_entry_point('pip==7.1.2', 'console_scripts', 'pip2.7')()
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/local/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/opt/local/lib/python2.7/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/opt/local/lib/python2.7/site-packages/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/opt/local/lib/python2.7/site-packages/pip/wheel.py", line 35, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/opt/local/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/opt/local/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module>
    from urllib2 import (Request, urlopen, URLError, HTTPError,
ImportError: cannot import name HTTPSHandler
```

The true error after digging

``` bash
[root@test ~]# python
Python 2.7.11 (default, Jan 11 2016, 23:16:55)
[GCC 4.9.3] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: ld.so.1: python2.7: fatal: relocation error: file /opt/local/lib/python2.7/lib-dynload/_ssl.so: symbol SSLv2_method: referenced symbol not found
>>>
```

**Comment by sjorge** [comment]
I was using base64-lts 14.4.0 and 15.4.0.

``` bash
pkgin -Fy in python27
```

Is a fix, it will reinstall the python27 package with a recompiled _ssl.so

**Comment by sjorge** [comment]
Marking it as closed as there is nothing more that can be done.
