### ISSUE TITLE
py2.7: urlopen error unknown url type: https

### ISSUE THREAD

**Issue by nifoc** [TritonDataCenter/pkgsrc-legacy#334]
**Zone:** 15.4.0-base (with just the latest base packages installed)

```
# uname -a
SunOS b789a0e9-f6df-4e96-87fa-b1ea123d473e 5.11 joyent_20151112T202630Z i86pc i386 i86pc Solaris
```

```
# python --version
Python 2.7.11
```

```
# python
Python 2.7.11 (default, Jan 11 2016, 23:16:55)
[GCC 4.9.3] on sunos5
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> urllib2.urlopen("https://google.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/opt/local/lib/python2.7/urllib2.py", line 454, in _open
    'unknown_open', req)
  File "/opt/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/opt/local/lib/python2.7/urllib2.py", line 1265, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib2.URLError: <urlopen error unknown url type: https>
```

It looks like maybe py2.7 was compiled without SSL support enabled?

**Comment by jperkin** [comment]
Hi Daniel,

This is an unfortunate side-effect of the OpenSSL update.  As the ABI changed it's necessary to reinstall packages that have been rebuilt against it.  The quick fix is to run:

```
# pkgin -F install python27
```

which will reinstall the rebuilt python package and your test case will then work.  The alternative is to use the new 15.4.1 images which were released last week, as they come included with all of the updated packages.
