### ISSUE TITLE
Regression: ruby21-chef has issues with ffi-yajl

### ISSUE THREAD

**Issue by jacques** [TritonDataCenter/pkgsrc-legacy#363]
```
# knife
/opt/local/lib/ruby/2.1.0/rubygems/specification.rb:1292:in `block in activate_dependencies': can't satisfy 'ffi-yajl (~> 1.2)', already activated 'ffi-yajl-2.2.2' (Gem::LoadError)
        from /opt/local/lib/ruby/2.1.0/rubygems/specification.rb:1284:in `each'
        from /opt/local/lib/ruby/2.1.0/rubygems/specification.rb:1284:in `activate_dependencies'
        from /opt/local/lib/ruby/2.1.0/rubygems/specification.rb:1266:in `activate'
        from /opt/local/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:54:in `gem'
        from /opt/local/bin/knife:22:in `<main>'
```

**Comment by jacques** [comment]
Filip / Jonathan Chef on Joyent is broken out of the gates atm.

**Comment by jacques** [comment]
Found a workaround (not using the pkgsrc.joyent.com chef builds now) but the illumos operations one (from http://us-east.manta.joyent.com/illumos/public/chef/chef-12.8.1-1.sunos.tar.gz).

**Comment by mamash** [comment]
Github autoclose, re-opening.
