### ISSUE TITLE
OpenJDK 1.8 SSL error

### ISSUE THREAD

**Issue by anilj** [TritonDataCenter/pkgsrc-legacy#367]
I have openjdk8-1.8.66nb1 installed.
I get this exception when trying to start Glassfish. Happened to a few different people too:
https://www.mail-archive.com/smartos-discuss@lists.smartos.org/msg02750.html

https://bugzilla.redhat.com/show_bug.cgi?id=1167153

Reproduce it with:
Download and unzip this file (as user test1):
http://download.java.net/glassfish/4.1.1/release/glassfish-4.1.1.zip

If you don't do this as root, make sure to allow test1 access to lower ports:
usermod -K defaultpriv=basic,net_privaddr test1

asadmin create-domain --adminport 4848 --instanceport 80 --domainproperties http.ssl.port=443 --domaindir /home/test1/domains test1
asadmin change-admin-password
asadmin --port 4848 enable-secure-admin
asadmin start-domain --domaindir /home/test1/domains test1

Login to https://host:4848

[2016-05-20T01:17:08.211+0000] [glassfish 4.1] [WARNING] [] [org.glassfish.grizzly.filterchain.DefaultFilterChain] [tid: _ThreadID=44 _ThreadName=admin-listener(4)] [timeMillis: 1463707028211] [levelValue: 900] [[
  GRIZZLY0013: Exception during FilterChain execution
java.lang.Error: BAD
        at sun.security.ssl.HandshakeHash.getFinishedHash(HandshakeHash.java:249)
        at sun.security.ssl.HandshakeMessage$Finished.getFinished(HandshakeMessage.java:1945)
        at sun.security.ssl.HandshakeMessage$Finished.verify(HandshakeMessage.java:1914)
        at sun.security.ssl.ServerHandshaker.clientFinished(ServerHandshaker.java:1679)
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:305)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1025)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at org.glassfish.grizzly.ssl.SSLUtils.sslEngineUnwrap(SSLUtils.java:460)
        at org.glassfish.grizzly.ssl.SSLConnectionContext.unwrap(SSLConnectionContext.java:189)
        at org.glassfish.grizzly.ssl.SSLUtils.handshakeUnwrap(SSLUtils.java:286)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:638)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.doHandshakeStep(SSLBaseFilter.java:587)
        at org.glassfish.grizzly.ssl.SSLBaseFilter.handleRead(SSLBaseFilter.java:304)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)

**Comment by mamash** [comment]
Good old erroneous auto-close by GitHub.
