### ISSUE TITLE
Mercurial broken when installed in base-multiarch

### ISSUE THREAD

**Issue by jcea** [TritonDataCenter/pkgsrc-legacy#424]
Image: base-multiarch 16.3.1

```
# python -c "import platform; print(platform.architecture())" -> ('32bit', 'ELF')
# pkgin install mercurial
[...]
# hg
Traceback (most recent call last):
  File "/opt/local/bin/hg", line 43, in <module>
    mercurial.util.setbinary(fp)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 147, in __getattribute__
    self._load()
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 96, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 53, in _hgextimport
    return importfunc(name, globals, *args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/util.py", line 120, in <module>
    statfiles = getattr(osutil, 'statfiles', platform.statfiles)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 147, in __getattribute__
    self._load()
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 96, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 53, in _hgextimport
    return importfunc(name, globals, *args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/__init__.py", line 120, in load_module
    mod = imp.load_module(name, *modinfo)
ImportError: ld.so.1: python2.7: fatal: /opt/local/lib/python2.7/site-packages/amd64/mercurial/osutil.so: wrong ELF class: ELFCLASS64
```

**Comment by mamash** [comment]
I'll have a look. Multiarch support for Python related packages is quite poor currently. This particular problem just doesn't manifest at build time (as in rrdtool), but at runtime.

**Comment by mamash** [comment]
This is fixed now in 2016Q3/multiarch. Please re-install py27-mercurial (make sure to clean the pkgin cache with `pkgin cl` before re-installing).
