### ISSUE TITLE
illumos variant broken on OmniOS

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc-legacy#427]
After install the illumos bootstrap on omnios and doing a pkgin install salt

Nothing works, pycrypto complains it cannot find the required libraries for the cbindings to work.
Likewise if manually installing using gcc47 or gcc49 they complain also. I guess there is some funcky LD_LIBRARY_PATH stuff going on.

```
root@sd-omni:/root# salt-call --local test.ping
Traceback (most recent call last):
  File "/opt/local/bin/salt-call", line 11, in <module>
    salt_call()
  File "/opt/local/lib/python2.7/site-packages/salt/scripts.py", line 346, in salt_call
    import salt.cli.call
  File "/opt/local/lib/python2.7/site-packages/salt/cli/call.py", line 6, in <module>
    from salt.utils import parsers
  File "/opt/local/lib/python2.7/site-packages/salt/utils/parsers.py", line 28, in <module>
    import salt.config as config
  File "/opt/local/lib/python2.7/site-packages/salt/config/__init__.py", line 41, in <module>
    import salt.utils.sdb
  File "/opt/local/lib/python2.7/site-packages/salt/utils/sdb.py", line 9, in <module>
    import salt.loader
  File "/opt/local/lib/python2.7/site-packages/salt/loader.py", line 30, in <module>
    import salt.utils.event
  File "/opt/local/lib/python2.7/site-packages/salt/utils/event.py", line 72, in <module>
    import salt.payload
  File "/opt/local/lib/python2.7/site-packages/salt/payload.py", line 17, in <module>
    import salt.crypt
  File "/opt/local/lib/python2.7/site-packages/salt/crypt.py", line 42, in <module>
    import salt.utils.rsax931
  File "/opt/local/lib/python2.7/site-packages/salt/utils/rsax931.py", line 69, in <module>
    libcrypto = _init_libcrypto()
  File "/opt/local/lib/python2.7/site-packages/salt/utils/rsax931.py", line 47, in _init_libcrypto
    libcrypto = _load_libcrypto()
  File "/opt/local/lib/python2.7/site-packages/salt/utils/rsax931.py", line 40, in _load_libcrypto
    raise OSError('Cannot locate OpenSSL libcrypto')
OSError: Cannot locate OpenSSL libcrypto
root@sd-omni:/root# which salt-call
/opt/local/bin/salt-call
```

Seems that pythons find_library() call is not picking up the library :s

**Comment by sjorge** [comment]
Seems to be a upstream issue. PR opened https://github.com/saltstack/salt/pull/37495
