### ISSUE TITLE
py27-lint is broken on 2016Q4

### ISSUE THREAD

**Issue by sjorge** [TritonDataCenter/pkgsrc-legacy#454]
```
[!]# pylint-2.7
Traceback (most recent call last):
  File "/opt/local/bin/pylint-2.7", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'backports.functools_lru_cache' distribution was not found and is required by pylint
```

Not found a fix yet

**Comment by sjorge** [comment]
Installing backports.functools-lru-cache via pip fixed the problem.
It looks like it is not available in pkgsrc so probably a new package needs to be create as a dependency for the newer pylint.

**Comment by mamash** [comment]
Yep, thanks for the tip. I just created a package py-lint in pkgsrc and all its dependencies. It will first show up in the 2017Q1 pkgsrc release though.

**Comment by mamash** [comment]
Just realized I was thrown off by 'py27-lint' and didn't see the package exists in pkgsrc as devel/py-pylint. I integrated my fixes into the existing one, but since a new package was added, the change will still show up in 2017Q1 only.
