### ISSUE TITLE
hg broken in multiarch 2014, 2015

### ISSUE THREAD

**Issue by rmustacc** [TritonDataCenter/pkgsrc-legacy#456]
I've been using the multiarch image for development. I recently had to do something with mercurial and tried to install and run it. While the install works, in both cases, it fails to run:

```
hg clone hg clone http://hg.nginx.org/nginx nginx-upstream
Traceback (most recent call last):
  File "/opt/local/bin/hg", line 41, in <module>
    mercurial.util.setbinary(fp)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 130, in __getattribute__
    self._load()
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 96, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 53, in _hgextimport
    return importfunc(name, globals, *args, **kwargs)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/util.py", line 77, in <module>
    statfiles = getattr(osutil, 'statfiles', platform.statfiles)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 130, in __getattribute__
    self._load()
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 96, in _load
    mod = _hgextimport(_import, head, globals, locals, None, level)
  File "/opt/local/lib/python2.7/site-packages/amd64/mercurial/demandimport.py", line 53, in _hgextimport
    return importfunc(name, globals, *args, **kwargs)
ImportError: ld.so.1: python2.7: fatal: /opt/local/lib/python2.7/site-packages/amd64/mercurial/osutil.so: wrong ELF class: ELFCLASS64
```

This happens in both 2014 Q4 an 2015 Q4 multiarch package sets. It may happen on 2016 Q4, but I don't have the image around at this moment.

**Comment by bahamat** [comment]
I think #424 is related.

**Comment by mamash** [comment]
Yes, it's a dup of #424, which only fixed the problem in 2016Q3 and newer releases (2016Q4/multiarch is fine). I think I can port this back to 2014Q4/2015Q4 if it's found helpful.

**Comment by rmustacc** [comment]
@mamash it'd be helpful to me at least, if it were backported.

**Comment by mamash** [comment]
The 2014Q4/multiarch branch is now fixed, 2015Q4 is building. You'll need to update the 'py27-mercurial' package (the one called simple 'mercurial' is just an empty shell).

**Comment by mamash** [comment]
2015Q4/multiarch finished too
