### ISSUE TITLE
py27-virtualenv in base64 behaves like it thinks it's multiarch

### ISSUE THREAD

**Issue by bahamat** [TritonDataCenter/pkgsrc-legacy#484]
Trying to use py27-virtualenv in a base-64-lts@16.4.1 image, generating a virtualenv has the following errors:

* `IOError: [Errno 2] No such file or directory: '/opt/local/bin/i86/python2.7'`
* `IOError: [Errno 2] No such file or directory: '/opt/local/bin/amd64/python2.7'`

After creating symlinks from `i86` and `amd64` in `/opt/local/bin` to itself it works.

<details>

    [root@graphite /opt]# virtualenv --system-site-packages graphite
    New python executable in /opt/graphite/bin/python2.7
    Traceback (most recent call last):
      File "/opt/local/bin/virtualenv-2.7", line 11, in <module>
        load_entry_point('virtualenv==15.1.0', 'console_scripts', 'virtualenv')()
      File "/opt/local/lib/python2.7/site-packages/virtualenv.py", line 713, in main
        symlink=options.symlink)
      File "/opt/local/lib/python2.7/site-packages/virtualenv.py", line 925, in create_environment
        site_packages=site_packages, clear=clear, symlink=symlink))
      File "/opt/local/lib/python2.7/site-packages/virtualenv.py", line 1245, in install_python
        shutil.copyfile(executable32, py_executable32)
      File "/opt/local/lib/python2.7/shutil.py", line 82, in copyfile
        with open(src, 'rb') as fsrc:
    IOError: [Errno 2] No such file or directory: '/opt/local/bin/i86/python2.7'
    [root@graphite /opt]# cd /opt/local/bin
    [root@graphite /opt/local/bin]# ln -s . i86
    [root@graphite /opt/local/bin]# cd -
    /opt
    [root@graphite /opt]# virtualenv --system-site-packages graphite
    New python executable in /opt/graphite/bin/python2.7
    Traceback (most recent call last):
      File "/opt/local/bin/virtualenv-2.7", line 11, in <module>
        load_entry_point('virtualenv==15.1.0', 'console_scripts', 'virtualenv')()
      File "/opt/local/lib/python2.7/site-packages/virtualenv.py", line 713, in main
        symlink=options.symlink)
      File "/opt/local/lib/python2.7/site-packages/virtualenv.py", line 925, in create_environment
        site_packages=site_packages, clear=clear, symlink=symlink))
      File "/opt/local/lib/python2.7/site-packages/virtualenv.py", line 1246, in install_python
        shutil.copyfile(executable64, py_executable64)
      File "/opt/local/lib/python2.7/shutil.py", line 82, in copyfile
        with open(src, 'rb') as fsrc:
    IOError: [Errno 2] No such file or directory: '/opt/local/bin/amd64/python2.7'
    [root@graphite /opt]# cd -
    /opt/local/bin
    [root@graphite /opt/local/bin]# ln -s . amd64
    [root@graphite /opt/local/bin]# cd -
    /opt
    [root@graphite /opt]# virtualenv --system-site-packages graphite
    New python executable in /opt/graphite/bin/python2.7
    Also creating executable in /opt/graphite/bin/python
    Installing setuptools, pip, wheel...done.

</details>

**Comment by jperkin** [comment]
Sorry about that, I've fixed this in 2016Q4, however you'll need to remove the package and re-install it, as it's still the same release version as trunk so we can't bump the revision.

**Comment by oddsignals** [comment]
I'm seeing this in 17.1.0 base-64

**Comment by jperkin** [comment]
Yeh, it was fixed in trunk and backported to 2016Q4, I didn't backport it to 2017Q1 though. I'll do this today.

**Comment by oddsignals** [comment]
Fantastic, thanks!

**Comment by jperkin** [comment]
This should now be available, run `pkg_add -U py27-virtualenv` to install a fixed package.
